/* Pulls admin-managed content from Postgres and regenerates
   _build/generated-content.mjs, which the page templates import. Run before
   `node _build/build.mjs` as part of a publish — see server/src/routes/publish.ts.
   Requires DATABASE_URL in the environment (same one the server uses). */
import fs from "fs";
import path from "path";
import pg from "pg";

const ROOT = path.resolve(new URL(".", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1"));

const esc = (s) => JSON.stringify(String(s ?? ""));

async function main() {
  const url = process.env.DATABASE_URL;
  if (!url) {
    console.log("fetchData: no DATABASE_URL set, leaving generated-content.mjs untouched");
    return;
  }
  const client = new pg.Client({ connectionString: url });
  await client.connect();
  try {
    const { rows } = await client.query(
      `select promo_video_url, promo_gift_title, promo_gift_body, promo_partner_url
       from site_media where id = 1`,
    );
    const row = rows[0] ?? {};

    // Operational fields only — status/progress/stage, the things that
    // actually change week to week. Editorial copy (taglines, CTA labels,
    // hero images) stays hand-authored in data.mjs; this overlays onto it
    // by slug, it doesn't replace it. See data.mjs's PROJECTS/CONSTRUCTION
    // merge for how the two combine.
    const { rows: projectRows } = await client.query(
      `select slug, status, completion_percent, current_stage, next_milestone
       from projects`,
    );
    const projectsLive = projectRows.map((p) => ({
      slug: p.slug,
      status: p.status,
      completionPercent: p.completion_percent,
      currentStage: p.current_stage,
      nextMilestone: p.next_milestone,
    }));

    // Marketing Feed (marketing.html) — fully DB-driven, no static fallback
    // content, since this is meant to be current/live, not evergreen copy.
    const { rows: marketingRows } = await client.query(
      `select id, title, body, media_url, campaign_tag, published_at
       from marketing_posts order by published_at desc`,
    );
    const marketingPosts = marketingRows.map((m) => ({
      id: m.id,
      title: m.title,
      body: m.body,
      mediaUrl: m.media_url,
      campaignTag: m.campaign_tag,
      publishedAt: m.published_at,
    }));

    const header = [
      "/* Regenerated by node _build/fetchData.mjs from the admin-managed",
      "   database before every publish. Checked in with safe fallbacks so",
      "   a fresh clone (or a DB-less build) still produces a working site. Never",
      "   hand-edit — your changes will be overwritten on the next publish. */",
    ].join("\n");
    const out = `${header}
export const PROMO = {
  videoUrl: ${esc(row.promo_video_url)},
  giftTitle: ${esc(row.promo_gift_title)},
  giftBody: ${esc(row.promo_gift_body)},
  partnerUrl: ${esc(row.promo_partner_url)},
};

// Keyed by project slug, overlaid onto data.mjs's PROJECTS/CONSTRUCTION —
// see mergeLiveProject() in data.mjs.
export const PROJECTS_LIVE = ${JSON.stringify(projectsLive, null, 2)};

// marketing.html's feed, newest first. No merge needed — rendered as-is.
export const MARKETING_POSTS = ${JSON.stringify(marketingPosts, null, 2)};
`;
    fs.writeFileSync(path.join(ROOT, "generated-content.mjs"), out);
    console.log(`fetchData: generated-content.mjs written from site_media + ${projectsLive.length} projects + ${marketingPosts.length} marketing posts`);
  } finally {
    await client.end();
  }
}

main().catch((err) => {
  console.error("fetchData failed:", err);
  process.exit(1);
});
