/* Pulls admin-managed content from Postgres and regenerates
   _build/generated-content.mjs, which the page templates import. Run before
   `node _build/build.mjs` as part of a publish — see server/src/routes/publish.ts.
   Requires DATABASE_URL in the environment (same one the server uses). */
import fs from "fs";
import path from "path";
import pg from "pg";

const ROOT = path.resolve(new URL(".", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1"));

const esc = (s) => JSON.stringify(String(s ?? ""));

async function main() {
  const url = process.env.DATABASE_URL;
  if (!url) {
    console.log("fetchData: no DATABASE_URL set, leaving generated-content.mjs untouched");
    return;
  }
  const client = new pg.Client({ connectionString: url });
  await client.connect();
  try {
    const { rows } = await client.query(
      `select promo_video_url, promo_gift_title, promo_gift_body, promo_partner_url
       from site_media where id = 1`,
    );
    const row = rows[0] ?? {};

    const header = [
      "/* Regenerated by node _build/fetchData.mjs from the admin-managed",
      "   site_media table before every publish. Checked in with safe fallbacks so",
      "   a fresh clone (or a DB-less build) still produces a working site. Never",
      "   hand-edit — your changes will be overwritten on the next publish. */",
    ].join("\n");
    const out = `${header}
export const PROMO = {
  videoUrl: ${esc(row.promo_video_url)},
  giftTitle: ${esc(row.promo_gift_title)},
  giftBody: ${esc(row.promo_gift_body)},
  partnerUrl: ${esc(row.promo_partner_url)},
};
`;
    fs.writeFileSync(path.join(ROOT, "generated-content.mjs"), out);
    console.log("fetchData: generated-content.mjs written from site_media");
  } finally {
    await client.end();
  }
}

main().catch((err) => {
  console.error("fetchData failed:", err);
  process.exit(1);
});
