/* Regenerated by `node _build/fetchData.mjs` from the admin-managed
   site_media table before every publish. Checked in with safe fallbacks so
   a fresh clone (or a DB-less build) still produces a working site. Never
   hand-edit — your changes will be overwritten on the next publish. */
export const PROMO = {
  videoUrl: "",
  giftTitle: "",
  giftBody: "",
  partnerUrl: "",
};
