/* Regenerated by node _build/fetchData.mjs from the admin-managed
   database before every publish. Checked in with safe fallbacks so
   a fresh clone (or a DB-less build) still produces a working site. Never
   hand-edit — your changes will be overwritten on the next publish. */
export const PROMO = {
  videoUrl: "",
  giftTitle: "",
  giftBody: "",
  partnerUrl: "",
};

// Keyed by project slug, overlaid onto data.mjs's PROJECTS/CONSTRUCTION —
// see mergeLiveProject() in data.mjs.
export const PROJECTS_LIVE = [];
